/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports the service version and whether it is running in demo mode.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports whether MHEAT is ready to serve **live** Copernicus data. In demo mode this is always ready. In live mode, the response is ``degraded`` until CMS credentials are set via environment.
         */
        get: operations["ready_api_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detected MHW events as GeoJSON FeatureCollection
         * @description Return all MHW events intersecting the optional spatial/temporal filter.
         *
         *     By default returns space-time clustered events (typically ~5-10 polygons
         *     for the 2022 Mediterranean demo). Pass ``raw=true`` to get the underlying
         *     per-pixel events (typically 50+ small rectangles).
         */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detected MHW events as a CSV download
         * @description Streams the same event catalog as ``/api/events`` but formatted as CSV (event_id, dates, intensities, category, impact metrics) for direct download into Excel / R / pandas.
         */
        get: operations["list_events_csv_api_events_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SST, climatology & threshold time-series around an event
         * @description Returns a short SST / climatology / 90th-percentile-threshold window around a single event at the given location. Used by the UI to draw a Hobday-style diagnostic chart in the event detail panel.
         */
        get: operations["event_series_api_events__event_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/processes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available processes
         * @description OGC-API-Processes style listing of the computation jobs MHEAT exposes.
         */
        get: operations["list_processes_api_processes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/processes/mhw-detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run MHW detection on the configured SST cube
         * @description Runs the Hobday 2016 pixel-wise detector on the configured SST cube for an optional bbox and temporal window, then joins the detected events with the sectoral overlays (`with_impact=true`).
         */
        post: operations["mhw_detect_api_processes_mhw_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overlays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supported overlay kinds
         * @description Enumerates the sectoral overlays available through `/api/overlays/{kind}`.
         */
        get: operations["list_kinds_api_overlays_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overlays/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch an overlay as GeoJSON
         * @description Returns a GeoJSON FeatureCollection for one of the sectoral overlays (`aquaculture`, `mpa`, `seagrass`). Geometries are pre-fetched from EMODnet / EEA WFS and cached locally.
         */
        get: operations["get_overlay_api_overlays__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stac/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List STAC collections
         * @description STAC Collections endpoint — enumerates every collection MHEAT publishes.
         */
        get: operations["collections_api_stac_collections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stac/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one STAC collection
         * @description Fetch the metadata document for a single STAC collection.
         */
        get: operations["get_collection_api_stac_collections__collection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stac/collections/{collection_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List items in a collection
         * @description Returns a STAC ItemCollection (GeoJSON FeatureCollection with STAC properties).
         */
        get: operations["list_items_api_stac_collections__collection_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stac/collections/{collection_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one STAC item
         * @description Fetch a single STAC Item by id.
         */
        get: operations["get_item_api_stac_collections__collection_id__items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomaly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SST anomaly PNG tile for a given date
         * @description Returns a PNG image of the SST anomaly (observation minus DOY climatology) for the requested date. Served with a long-lived ``Cache-Control: immutable`` header plus an ETag so the client never needs to re-download the same tile.
         */
        get: operations["anomaly_png_api_anomaly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomaly/extent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Temporal extent covered by the anomaly endpoint
         * @description Returns the date range the anomaly endpoint can serve.
         */
        get: operations["anomaly_extent_api_anomaly_extent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ogcapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OGC API Features landing page
         * @description Entry point exposing links to conformance, collections, and API docs.
         */
        get: operations["landing_api_ogcapi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ogcapi/conformance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OGC API Features conformance classes
         * @description Lists the OGC API Features conformance classes implemented by this service.
         */
        get: operations["conformance_api_ogcapi_conformance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ogcapi/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List OGC API feature collections
         * @description Enumerates all OGC API feature collections (events, aquaculture, mpa, seagrass).
         */
        get: operations["list_collections_api_ogcapi_collections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ogcapi/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch OGC collection metadata
         * @description Returns metadata (title, description, extent, CRS) for a single collection.
         */
        get: operations["get_collection_api_ogcapi_collections__collection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ogcapi/collections/{collection_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List features (paged)
         * @description Returns a paged GeoJSON FeatureCollection. Supports ``bbox``, ``datetime``, ``limit`` (max 1000) and ``offset``. A ``next`` link header is emitted when more features are available.
         */
        get: operations["list_items_api_ogcapi_collections__collection_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ogcapi/collections/{collection_id}/items/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a single feature
         * @description Retrieve one feature from a collection by its ``id``.
         */
        get: operations["get_item_api_ogcapi_collections__collection_id__items__feature_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DetectInputs
         * @description Input payload for the mhw-detect process.
         */
        DetectInputs: {
            /**
             * Bbox
             * @description [lon_min, lat_min, lon_max, lat_max]
             */
            bbox?: number[] | null;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /**
             * Min Category
             * @default 1
             */
            min_category: number;
            /**
             * With Impact
             * @description Compute overlay intersections
             * @default true
             */
            with_impact: boolean;
        };
        /**
         * DetectResponse
         * @description Response envelope for the mhw-detect process.
         */
        DetectResponse: {
            /** Status */
            status: string;
            /** N Events */
            n_events: number;
            /** Events */
            events: Record<string, never>;
            /** Impact */
            impact?: Record<string, never> | null;
        };
        /** EventCollection */
        EventCollection: {
            /**
             * Type
             * @default FeatureCollection
             */
            type: string;
            /** Features */
            features: components["schemas"]["EventFeature"][];
        };
        /** EventFeature */
        EventFeature: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            /** Id */
            id: string;
            /** Geometry */
            geometry: Record<string, never>;
            properties: components["schemas"]["EventProperties"];
        };
        /** EventProperties */
        EventProperties: {
            /** Event Id */
            event_id: string;
            /** Date Start */
            date_start: string;
            /** Date End */
            date_end: string;
            /** Date Peak */
            date_peak: string;
            /** Duration Days */
            duration_days: number;
            /** Intensity Max */
            intensity_max: number;
            /** Intensity Mean */
            intensity_mean: number;
            /** Intensity Cumulative */
            intensity_cumulative: number;
            /** Category */
            category: number;
            /** Category Name */
            category_name: string;
            /**
             * N Pixels
             * @default 1
             */
            n_pixels: number;
            /** Centroid */
            centroid: number[];
            /** Impact */
            impact?: Record<string, never> | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Basic liveness response.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Demo Mode */
            demo_mode: boolean;
        };
        /**
         * ReadyResponse
         * @description Readiness response — reports whether CMS credentials are wired up.
         */
        ReadyResponse: {
            /** Status */
            status: string;
            /** Demo Mode */
            demo_mode: boolean;
            /** Cms Credentials */
            cms_credentials: boolean;
            /** Cache Dir */
            cache_dir: string;
            /** Zarr Store */
            zarr_store: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 OK whenever the process is responsive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Readiness status + cache-path diagnostics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                /** @description lon_min,lat_min,lon_max,lat_max */
                bbox?: string | null;
                /** @description YYYY-MM-DD */
                start?: string | null;
                /** @description YYYY-MM-DD */
                end?: string | null;
                min_category?: number;
                /** @description Return raw per-pixel events instead of clusters */
                raw?: boolean;
                /** @description Attach per-event impact metrics */
                include_impact?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_csv_api_events_csv_get: {
        parameters: {
            query?: {
                /** @description lon_min,lat_min,lon_max,lat_max */
                bbox?: string | null;
                /** @description YYYY-MM-DD */
                start?: string | null;
                /** @description YYYY-MM-DD */
                end?: string | null;
                min_category?: number;
                /** @description Return raw per-pixel events instead of clusters */
                raw?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file (text/csv) with one row per event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_series_api_events__event_id__series_get: {
        parameters: {
            query: {
                /** @description Longitude in decimal degrees */
                lon: number;
                /** @description Latitude in decimal degrees */
                lat: number;
                /** @description Days to pad around the event */
                pad_days?: number;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON with parallel arrays: time, sst, clim, threshold */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_processes_api_processes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of process descriptors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    mhw_detect_api_processes_mhw_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectInputs"];
            };
        };
        responses: {
            /** @description Envelope with per-event GeoJSON + optional impact summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_kinds_api_overlays_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of overlay identifiers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_overlay_api_overlays__kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GeoJSON FeatureCollection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collections_api_stac_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description STAC-style JSON with a `collections` array */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_collection_api_stac_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description STAC Collection object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_stac_collections__collection_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description STAC ItemCollection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_stac_collections__collection_id__items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description STAC Item (GeoJSON Feature with STAC properties) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anomaly_png_api_anomaly_get: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD */
                date: string;
                /** @description Reserved; bbox currently ignored in demo mode */
                bbox?: string | null;
            };
            header?: {
                "If-None-Match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG image (image/png) with ETag and Cache-Control headers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Not modified (ETag matched) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Date out of range */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anomaly_extent_api_anomaly_extent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description First & last available date plus colour-scale range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    landing_api_ogcapi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    conformance_api_ogcapi_conformance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_collections_api_ogcapi_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_collection_api_ogcapi_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_ogcapi_collections__collection_id__items_get: {
        parameters: {
            query?: {
                /** @description lon_min,lat_min,lon_max,lat_max */
                bbox?: string | null;
                /** @description RFC3339 instant or interval */
                datetime?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_ogcapi_collections__collection_id__items__feature_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
