{{- if or .Values.cmsSecret.username .Values.cmsSecret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cmsSecret.name }}
type: Opaque
stringData:
  {{ .Values.cmsSecret.usernameKey }}: {{ .Values.cmsSecret.username | quote }}
  {{ .Values.cmsSecret.passwordKey }}: {{ .Values.cmsSecret.password | quote }}
{{- end }}
